server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1031257684665-knkr9fbcoeud3gg55hc3kr47cd2n2g2q.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile

          facebook:
            client-id: 1244402233617077
            client-secret: 1df7576faa58e429bfdaaeefe68842c1
            scope:
              - email
              - public_profile

          naver:
            client-id: g1U5lR4UnvavwMI5XS1Y
            client-secret: DKnleHE7mY
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code # code를 받아와서 인증
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원 정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌.